[package]
name = "private_transfer_zkp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellman = "0.10.0"
pairing = "0.20"
rand = "0.8.5"
curve25519-dalek = "3.2.0"

